# Generated by Django 5.0.3 on 2024-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Nature', 'Nature'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Animals', 'Animals'), ('Technology', 'Technology'), ('Science', 'Science'), ('Culture', 'Culture'), ('Music', 'Music'), ('Entertainment', 'Entertainment'), ('History', 'History'), ('Fiction', 'Fiction'), ('Art', 'Art'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
