# Generated by Django 5.0.3 on 2024-04-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modify',
            field=models.DateTimeField(default=None),
        ),
    ]
