# Generated by Django 5.0.3 on 2024-03-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Nature', 'Nature'), ('IT', 'IT'), ('Food', 'Food'), ('Fashion', 'Fashion')], max_length=20, null=True),
        ),
    ]
