# Generated by Django 5.0.3 on 2024-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.BooleanField(default=False),
        ),
    ]
