# Generated by Django 5.0.3 on 2024-03-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_to_reply',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.reply'),
        ),
    ]
