# Generated by Django 5.0.3 on 2024-03-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_categories_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
