# Generated by Django 5.0.3 on 2024-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_delete_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Regular Contributor', 'Regular Contributor'), ('Active Participant', 'Active Participant'), ('Community Leader', 'Community Leader'), ('Superuser', 'Superuser'), ('Moderator', 'Moderator')], default=None, max_length=30),
        ),
    ]
