# Generated by Django 5.0.3 on 2024-03-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_grade_rename_modified_post_last_modify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Regular Contributor', 'Regular Contributor'), ('Active Participant', 'Active Participant'), ('Community Leader', 'Community Leader'), ('Superuser', 'Superuser'), ('Moderator/Administrator', 'Moderator/Administrator')], default=None, max_length=30),
        ),
    ]
