# Generated by Django 5.0.3 on 2024-04-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_post_last_modify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_modify',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
