# Generated by Django 5.0.3 on 2024-03-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_user_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='pub_date',
        ),
    ]
